<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>cv.boot.html</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
    <style>
        * {
            padding: 0;
            margin: 0;
            font-family: sans-serif;
        }

        H4 {
            background-color: rgb(13, 29, 48);
            color: white;
            border-radius: 5px;
           text-align: center;
           padding: 8px;
           box-shadow: black 2px 2px 10px 1px;
        }
        .profile{text-align: center;}
        h3{text-shadow: rgb(45, 41, 82)}
        .ak_main{
            padding-top: 10px;
            background-color: rgb(245, 216, 178);
        }
    </style>
</head>

<body>
    <div class="container ak_main ">
        <div class="row">
            <div class="col-lg-4 col-sm-12 col_1">
                <div class="profile">
                <img src="Ravi.png">
                </div>
                <hr>
                <h3><b>ARJUN KUMAR</b></h3>
                <a href="https://mail.google.com/mail/u/0/#inbox" target="blank">arjunkumar87445@gmail.com</a>
                <ol>
                    <p><b>Contact No: </b>+91 7460865705</p>
                    <p><b>Date of Birth : </b> 05 january 2000</p>
                    <p><b>Gender : </b> Male</p>
                    <p><b>Language known : </b>Hindi,English</p>
                    <p><b>Hobbies : </b>Internet surfing, Music</p>
                    <p><b>Address : </b> Pure Gobre Po chauri alladadpur 
                        RSG Barabanki</p>

            </div>
            <div class="col-lg-8 col-sm-12 col-a1">
                <h4>SUMMARY:</h4>
                <p>	B.Tech graduate from BNCET, Lucknow.</p>
                <p>Developer to further enhance organizational worth by leveraging my skills and
                    knowledge in Front-end and Back-end development, Responsive frameworks, Coding,
                    Designing and maintaining Databases to enhance the client experience. </p>
                <p>Research oriented, highly motivated, smart and hungry to create new things. </p>
                <div class="row">
                    <div class="col-lg-6 col-sm-12 col_2">
                        <h4>Education Detail: </h4>
                        <p>B.Tech IT [2021] from BNCET, LUCKNOW. [AKTU University]</p>
                        <p>10+2 with Maths [2017] S.R.J.I.C PATRANGA MANDI FAIZABAD [U.P. board]  </p>
                        <p>High School [2015] from S.J.L.N.S.H.S.S. DEVIGANJ BARABANKI [U.P. board] </p>
                        <hr>
                        <h4>Technical Skills: </h4>
                        <span>
                            <p><b>Programming Languages/ Technologies:</b> C, HTML, CSS, Javascript Python</p>
                        </span>
                        <span>
                            <p><b>Operating Systems:</b> Windows 10, Windows 7</p>
                        
                        </span>
                        <span>
                            <p><b> Databases: </b> SQL</p>
                        </span>
                        <span>
                            <p><b>Softwares:</b> SolarWinds, ServiceNow, Microsoft Office (Word, PowerPoint, Excel,
                                Access),
                                Adobe Photoshop, Microsoft Visual Studio</p>
                        </span>
                        <span>
                            <p><b> Others:</b>Bootstrap</p>
                        </span><hr>
                        <h4>College Projects Detail:</h4>
                        <b>GiveBlood :</b>
                        <span>
                            <p><b> Duration: </b>Jan 2019 – Feb 2019</p>
                        </span>
                        <span>
                            <p><b> Team Size: </b>2</p>
                        </span>
                        <span>
                            <p><b> Role Played: </b>: Developer and Designer </p>
                        </span><hr>
                    </div>
                    <div class="col-lg-6 col-sm-12 col_3">
                        <h4>SKILLS USED</h4>
                        <p> HTML, CSS, JavaScript, Php
                            Give Blood system is an online blood bank management system that helps a blood bank in
                            managing various blood bank operations effectively. The entire project has been developed
                            keeping in view of the distributed client-server computing technology, in mind. Any person
                            who is interested in donating the blood can register himself.
                        </p><hr>

                        <h4>Strengths: </h4>
                        <p>A good Leader. </p>
                        <p>Good teaching skills </p>
                        <p>A high tolerance of stress. </p>
                        <p>Highly motivated.</p>
                        <p> A dreamer but down to earth. </p><hr>

                        <h4>Achievements:</h4>
                        <p>Won more than 5 medals in different competitions at school Level</p><hr>
                        <h4>Extra-Curricular:</h4>
                        <p>Freelance Computer/Laptop software troubleshooting. </p>
                        <p>Freelance Website/ Graphic designing. </p><hr>
                    </div>
                </div>
            </div>

        </div>
    </div>
</body>

</html>
